### ISSUE TITLE
German Wikipedia Background Image

### ISSUE THREAD

**Issue by tg--** [StylishThemes/Wikipedia-Dark#32] opened 2018-04-11 00:41 UTC
Unfortunately the German branch of Wikipedia uses a very slightly different CSS that sets a header background image when logged in to edit.

![wiki1](https://user-images.githubusercontent.com/462971/38590464-9afd3b10-3d31-11e8-9c17-3592b404ed68.png)

It would be great if a workaround for this could be added, the relevant CSS is:
```
div#globalWrapper {
    background-image: none;
}
```
After:
![wiki2](https://user-images.githubusercontent.com/462971/38590498-c7028e2c-3d31-11e8-9977-d1c3cad8c255.png)

**Comment by Mottie** [comment] 2018-04-11 01:00
Hi @tg--!

Oddly, I'm not seeing this issue. Do you have v1.0.35 installed?

![](https://user-images.githubusercontent.com/136959/38590936-d79d097a-3cf9-11e8-9873-e1737be7123b.png)

**Comment by tg--** [comment] 2018-04-11 01:06
Indeed I do, I just reinstalled it to confirm.
That is very strange.

I don't have any other userstyles that apply to wikipedia active, can't really tell why it's behaving so differently.

**Comment by tg--** [comment] 2018-04-11 01:07
I'm using Firefox and the xStyle extension btw.

**Comment by Mottie** [comment] 2018-04-11 01:25
I just tested our style on Firefox with xStyle and it still looks fine to me. So odd.

I did have to remove all privacy settings in Firefox to get it working properly, but it wasn't applying any style until I did that, so I doubt that's the problem.

**Comment by tg--** [comment] 2018-04-11 20:12
I just created a fresh firefox profile, installed nothing but xstyle + wikipedia-dark and still see the issue.
Really no clue why this isn't working for me while it is for you.

If nobody else can reproduce this I'll probably just carry my own workaround, probably doesn't make much sense to add it for everyone.

**Comment by Poorchop** [comment] 2018-04-13 15:19
I just tested and I can't reproduce. It probably won't make a difference since Mottie couldn't reproduce with xStyle, but try Stylus. When I was using the webextension version of Stylish, I was having issues that weren't present at all with Stylus.

**Comment by the-j0k3r** [comment] 2018-06-19 00:17
Its the fonts... Wanna bet?

**Comment by Mottie** [comment] 2018-07-13 22:30
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed by Mottie** 2018-07-13 22:30 UTC
